---
version: '3'

services:
    keycloak:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: -b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm.json
        privileged: true
        ports:
            - 8080:8080
        volumes:
            - ./sso:/opt/jboss/keycloak/themes/sso
            - ./imports:/opt/jboss/keycloak/imports
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin